document.getElementById('')
document.getElementsByClassName('')
document.querySelector('#')
document.querySelector('.')
document.querySelectorAll('#')
document.querySelectorAll('.')
document.getElementsByTagName('')